#Практическая работа №4
##Тема: «Линейная регрессия»
##Выполнил студент: Байтоков Ниязбек
##ВАРИАНТ: Pokemon.csv, https://raw.githubusercontent.com/NiyazBD/SystemAI_Baytokov/main/Practice2/Pokemon.csv

###Задание 1. Загрузить данные из dataset "Титаник"

In [18]:
from sklearn.metrics import classification_report, confusion_matrix

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import seaborn as sns

import warnings

url = "https://raw.githubusercontent.com/SpirinIgor/System-AI/main/Practice2/Datasets/titanic_train.csv"
mainDf = pd.read_csv(url)

###Задание 2. Произвести предобработку данных dataset "Титаник" и сохранить результаты каждый в отдельный датафрейм

####1.Удалить все пуcтые значения и сохранить результаты в датафрейм df_del

In [19]:
df_del = mainDf.dropna()

####2.Замена на конкретное значение все пуcтые и сохранить результаты в датафрейм df_num

In [20]:
df_num = mainDf.fillna(123456789)

####3.Заменить все пуcтые значения на среднее значение и сохранить результаты в датафрейм df_means

In [21]:
mainDf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [22]:
df_means = mainDf.fillna(mainDf.Age.mean())
df_means

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,29.699118,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,29.699118,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,29.699118,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,29.699118,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,29.699118,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,29.699118,Q

####4.Заменить все путые заначения на медеанные значение и сохранить результаты в датафрейм df_medians

In [23]:
df_medians = mainDf.fillna(mainDf.Age.median())
df_medians

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,28.0,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,28.0,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,28.0,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,28.0,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,28.0,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,28.0,Q

####5.Замена на предыдущее или следующее значение и сохранить результаты в датафрейм df_fb_fill

In [24]:
df_fb_fill = mainDf.fillna(method="ffill")
df_fb_fill

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C85,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,C50,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.4500,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,C148,Q

###Задание 3. Приметить к каждому датафрейму алгоритм линейной регресси

####df_del Пример Сани

In [ ]:
# Модель df_del
# Игнорировать все предупреждения
warnings.filterwarnings('ignore')

# Фильтрация данных возраста
df_del_25 = df_del[df_del['Age'] == 25]

# Подготовка данных: выбор признаков и целевой переменной
X1 = df_del_25[['Pclass', 'Sex', 'Embarked', 'Fare']]
y1 = df_del_25['Survived']

# Преобразование категориальных переменных в числовые
X1['Sex'] = X1['Sex'].map({'male': 0, 'female': 1})
X1['Embarked'] = X1['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

# Стандартизация признаков
scaler = StandardScaler()
X1_scaled = scaler.fit_transform(X1)

# Разделение данных на обучающую и тестовую выборки
X1_train, X1_test, y1_train, y1_test = train_test_split(X1_scaled, y1, test_size=0.2, random_state=42)

# Построение и обучение модели
model1 = LogisticRegression()
model1.fit(X1_train, y1_train)

# Предсказание на тестовых данных
y1_pred = model1.predict(X1_test)

пример Спирина

In [28]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

from sklearn.metrics import accuracy_score, recall_score, f1_score

import warnings
# Игнорировать все предупреждения
warnings.filterwarnings('ignore')

# Пример данных
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]]) # Независимые переменные
y = np.dot(X, np.array([1, 2])) + 3 # Зависимая переменная

# Разделение данных на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Создание и обучение модели линейной регрессии
model = LinearRegression()
model.fit(X_train, y_train)

# Прогнозирование на тестовых данных
y_pred = model.predict(X_test)

# Вывод коэффициентов модели
print("Коэффициенты модели:", model.coef_)
print("Свободный член модели:", model.intercept_)

# Оценка модели
accuracy = accuracy_score(np.round(y_test), np.round(y_pred))
recall = recall_score(np.round(y_test), np.round(y_pred))
f1 = f1_score(np.round(y_test), np.round(y_pred))

print(f"Accuracy: {accuracy}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

Коэффициенты модели: [1. 2.]
Свободный член модели: 3.0
Accuracy: 1.0
Recall: 0.0
F1 Score: 0.0

df_del linear regression

In [37]:
# Игнорировать все предупреждения
warnings.filterwarnings('ignore')

# Пример данных
X = df_del[['Survived']] # Независимые переменные
y = df_del[['Pclass']] # Зависимая переменная

# Разделение данных на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Создание и обучение модели линейной регрессии
model = LinearRegression()
model.fit(X_train, y_train)

# Прогнозирование на тестовых данных
y_pred = model.predict(X_test)

# Вывод коэффициентов модели
print("Коэффициенты модели:", model.coef_)
print("Свободный член модели:", model.intercept_)

# Оценка модели
accuracy = accuracy_score(np.round(y_test), np.round(y_pred))
recall = recall_score(np.round(y_test), np.round(y_pred))
f1 = f1_score(np.round(y_test), np.round(y_pred))

print(f"Accuracy: {accuracy}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

Коэффициенты модели: [[-0.07324001]]
Свободный член модели: [1.24528302]

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].